id: rconfig-ajaxarchivefiles-php-----------
info:
  author: pocscanner
  description: rConfig ajaxArchiveFiles.php文件中由于对path参数和ext参数进行命令拼接，导致攻击者可以远程命令执行获取服务器权限
  name: rConfig ajaxArchiveFiles.php 后台远程命令执行漏洞
  reference: []
  severity: critical
requests:
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/home/rconfig/config/functions.inc.php'
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/home/rconfig/www/lib/ajaxHandlers/ajaxArchiveFiles.php'
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/lib/ajaxHandlers/ajaxArchiveFiles.php'
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/home/rconfig/classes/usersession.class.php'
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/home/rconfig/classes/ADLog.class.php'
