id: rconfig-useradmin-inc-php-------
info:
  author: pocscanner
  description: rConfig useradmin.inc.php 存在信息泄露漏洞，通过访问文件获取用户邮箱信息和登录名
  name: rConfig useradmin.inc.php 信息泄露漏洞
  reference: []
  severity: medium
requests:
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/classes/paginator.class.php'
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/classes/db2.class.php'
- matchers:
  - status:
    - 200
    - 301
    - 302
    - 403
    type: status
  method: GET
  path:
  - '{{BaseURL}}/useradmin.inc.php'
